---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a backup client to a host
      dimensiondata_backup_client:
        server_ids:
          - '7ee719e9-7ae9-480b-9f16-c6b5de03463c'
        client_type: 'FA.Linux'
        storage_policy: '14 Day Storage Policy'
        schedule_policy: '12AM - 6AM'
        state: present
