---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create Load Balancer Pool
      dimensiondata_load_balancer_pool:
        region: na
        location: NA12
        network_domain: ansible-capabilities-demo
        name: lb01_pool01
        description: a pool yo
        load_balance_method: ROUND_ROBIN
        health_monitor_1: Http
        health_monitor_2: Tcp
        service_down_action: DROP
        slow_ramp_time: 23
        members:
          node1:
            ip: 10.1.1.4
            port: 80
          node2:
            ip: 10.1.1.5
            port: 80
#          node3:
#            ip: 10.1.1.134
#            port: 8080
        ensure: present
