---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - dimensiondata_vlan:
      region: na
      location: NA12
      network_domain: my_net_domain
      name: my_vlan1
      action: read
    register: vlan_result
  - block:
    - dimensiondata_vlan:
        region: na
        location: NA12
        private_ipv4_prefix_size: 23
        network_domain: my_net_domain
        vlan_id: "{{ vlan_result['vlan']['id'] }}"
        action: expand
