---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Delete MCP 1.0 network
      dimensiondata_network:
        region: na
        location: NA5
        name: ansible-test1
        state: absent
    - name: Delete MCP 2.0 network
      dimensiondata_network:
        region: na
        location: NA12
        name: ansible-test2
        state: absent
