---
- hosts: 127.0.0.1
  connection: local
  tasks:
# Delete public IP Block by block ID.
  - dimensiondata_public_ip_block:
      region: na
      location: NA12
      network_domain: testing_network111
      action: delete
      block_id: 62800068-0000-0000-0000-b8ca3a5d9ef8
